# Site settings
title: Nishant Sharma
email: nsharma@cse.unl.edu
description: > # this means to ignore newlines until "baseurl:"
  I am currently a graduate student at UNL. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nishantsharma.me" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  SharmaNishant

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
